package org.vhanma.dnaforgemax;

import android.app.Activity;
import android.content.ContentResolver;
import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.ImageDecoder;
import android.graphics.Movie;
import android.media.MediaMetadataRetriever;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.os.SystemClock;
import android.view.Gravity;
import android.view.View;
import android.view.WindowManager;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;

/** v9: prepare expensive geometry first, then play prebuilt trace frames at an exact clock. */
public class UltraV9Activity extends Activity {
    private static final int REQ_OPEN=9101,REQ_SAVE=9102;private static final int NONE=0,IMAGE=1,VIDEO=2,GIF=3;
    private V8FrameScopeView scope;private ImageView sourcePreview;private TextView status;private Button playButton;
    private Spinner sampleSpinner,fpsSpinner,profileSpinner,bandsSpinner,exportSpinner;private SeekBar qualityBar,structureBar,toneBar,gammaBar,intensityBar,beamBar,xGainBar,yGainBar,rotationBar;private TextView qualityLabel,structureLabel,toneLabel,gammaLabel,intensityLabel,beamLabel,xGainLabel,yGainLabel,rotationLabel;private CheckBox borderBox,invertBox,sourceBox,colorBox;
    private final ExecutorService worker=Executors.newSingleThreadExecutor();private final AtomicBoolean playing=new AtomicBoolean(false),preparing=new AtomicBoolean(false),cancelPrepare=new AtomicBoolean(false);private final AtomicInteger configGen=new AtomicInteger(1);private final V9PreparedAudio audio=new V9PreparedAudio();private Thread playbackThread;private boolean uiChanging=false;
    private Uri sourceUri;private int sourceKind=NONE;private Bitmap stillBitmap;private Movie gifMovie;private byte[]gifBytes;private MediaMetadataRetriever retriever;private long durationMs;private int sourceWidth,sourceHeight;
    private File cacheFile;private volatile boolean cacheReady=false;private int cacheGen=-1;private V9TraceEngine.Settings cacheSettings;

    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);setContentView(buildUi());status.setText("v9 ready. PLAY prepares stable trace geometry first, then streams it at a true fixed frame clock. No image analysis occurs during playback.");}

    private View buildUi(){int pad=dp(10);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(pad,pad,pad,pad);root.setBackgroundColor(Color.rgb(1,3,6));TextView title=label("OSCIVISION REFERENCE TRACE v9");title.setTextSize(25);title.setGravity(Gravity.CENTER_HORIZONTAL);title.setTextColor(Color.rgb(205,255,224));root.addView(title);TextView sub=label("PRECOMPUTED GEOMETRY • STABLE TRAVERSAL • TRUE 60 FPS PLAYBACK");sub.setTextSize(10.5f);sub.setGravity(Gravity.CENTER_HORIZONTAL);sub.setTextColor(Color.rgb(112,225,166));root.addView(sub);
        sourcePreview=new ImageView(this);sourcePreview.setScaleType(ImageView.ScaleType.CENTER_INSIDE);sourcePreview.setBackgroundColor(Color.BLACK);root.addView(sourcePreview,new LinearLayout.LayoutParams(-1,dp(145)));scope=new V8FrameScopeView(this);root.addView(scope,new LinearLayout.LayoutParams(-1,dp(455)));
        LinearLayout actions=row();Button load=button("LOAD");playButton=button("PREPARE + PLAY");Button save=button("Ω TRACE WAV");Button cal=button("CAL CIRCLE");actions.addView(load,weight());actions.addView(playButton,weight());actions.addView(save,weight());actions.addView(cal,weight());root.addView(actions);load.setOnClickListener(v->openMedia());playButton.setOnClickListener(v->togglePlay());save.setOnClickListener(v->chooseSave());cal.setOnClickListener(v->showCal());
        sourceBox=check("Show source reference",true);sourceBox.setOnCheckedChangeListener((b,v)->sourcePreview.setVisibility(v?View.VISIBLE:View.GONE));root.addView(sourceBox);colorBox=check("Use source colors in software trace",true);colorBox.setOnCheckedChangeListener((b,v)->scope.setColorPreview(v));root.addView(colorBox);
        root.addView(section("REFERENCE PLAYBACK"));sampleSpinner=spinner(new String[]{"192000 Hz · maximum trace density","96000 Hz","48000 Hz"},0);root.addView(sampleSpinner);fpsSpinner=spinner(new String[]{"60 fps · reference smooth","30 fps · double detail","24 fps · cinematic detail","20 fps · heavy detail","15 fps · maximum detail"},0);root.addView(fpsSpinner);profileSpinner=spinner(new String[]{"REFERENCE VIDEO / ANIME","PORTRAIT / CHARACTER","PHOTO + HATCH TONE","LINE / INK"},0);root.addView(profileSpinner);bandsSpinner=spinner(new String[]{"2 luminance shells","3 luminance shells","4 luminance shells","5 luminance shells","6 luminance shells","7 luminance shells","8 luminance shells"},3);root.addView(bandsSpinner);
        root.addView(section("TRACE COMPILER"));qualityLabel=label("VECTOR DETAIL: 94%");root.addView(qualityLabel);qualityBar=slider(94,v->{qualityLabel.setText("VECTOR DETAIL: "+v+"%");changed();});root.addView(qualityBar);structureLabel=label("STRUCTURE PRIORITY: 98%");root.addView(structureLabel);structureBar=slider(98,v->{structureLabel.setText("STRUCTURE PRIORITY: "+v+"%");changed();});root.addView(structureBar);toneLabel=label("TONE / HATCH: 38%");root.addView(toneLabel);toneBar=slider(38,v->{toneLabel.setText("TONE / HATCH: "+v+"%");changed();});root.addView(toneBar);borderBox=check("Suppress frame / panel rectangles",true);borderBox.setOnCheckedChangeListener((b,v)->changed());root.addView(borderBox);invertBox=check("Invert luminance",false);invertBox.setOnCheckedChangeListener((b,v)->changed());root.addView(invertBox);gammaLabel=label("IMAGE GAMMA: 0.90");root.addView(gammaLabel);gammaBar=new SeekBar(this);gammaBar.setMax(180);gammaBar.setProgress(50);gammaBar.setOnSeekBarChangeListener(change((b,v)->{gammaLabel.setText(String.format(Locale.US,"IMAGE GAMMA: %.2f",gamma()));changed();}));root.addView(gammaBar);
        root.addView(section("SCOPE"));intensityLabel=label("TRACE INTENSITY: 94%");root.addView(intensityLabel);intensityBar=sliderNoInvalidate(94,v->{intensityLabel.setText("TRACE INTENSITY: "+v+"%");scope.setIntensity(v);});root.addView(intensityBar);beamLabel=label("BEAM WIDTH: 22%");root.addView(beamLabel);beamBar=sliderNoInvalidate(22,v->{beamLabel.setText("BEAM WIDTH: "+v+"%");scope.setBeamWidth(v);});root.addView(beamBar);xGainLabel=label("X GAIN: 100%");root.addView(xGainLabel);xGainBar=gain(xGainLabel,"X GAIN");root.addView(xGainBar);yGainLabel=label("Y GAIN: 100%");root.addView(yGainLabel);yGainBar=gain(yGainLabel,"Y GAIN");root.addView(yGainBar);rotationLabel=label("ROTATION: 0.0°");root.addView(rotationLabel);rotationBar=new SeekBar(this);rotationBar.setMax(240);rotationBar.setProgress(120);rotationBar.setOnSeekBarChangeListener(change((b,v)->{rotationLabel.setText(String.format(Locale.US,"ROTATION: %.1f°",rotation()));changed();}));root.addView(rotationBar);
        root.addView(section("EXPORT"));exportSpinner=spinnerNoInvalidate(new String[]{"32-bit float WAV","24-bit PCM WAV"},0);root.addView(exportSpinner);TextView note=label("Playback never vectorizes a frame. The entire clip is converted into fixed-size trace blocks first, then AudioTrack receives them at the exact selected frame rate. v9 uses deterministic connected contours and sparse tone hatching instead of v8's point cloud. Large jumps are one-sample flybacks. LEFT=X, RIGHT=Y.");note.setTextSize(11);note.setTextColor(Color.rgb(132,168,152));root.addView(note);status=new TextView(this);status.setTextColor(Color.rgb(198,255,222));status.setTextSize(12.2f);status.setPadding(0,dp(7),0,dp(24));root.addView(status);ScrollView scroll=new ScrollView(this);scroll.addView(root);return scroll;}

    private TextView label(String s){TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.rgb(192,221,208));t.setTextSize(12);t.setPadding(0,dp(4),0,dp(2));return t;}private TextView section(String s){TextView t=label(s);t.setTextColor(Color.rgb(158,248,190));t.setTextSize(13);t.setPadding(0,dp(10),0,dp(2));return t;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(9.2f);return b;}private CheckBox check(String s,boolean v){CheckBox b=new CheckBox(this);b.setText(s);b.setTextColor(Color.rgb(205,231,218));b.setChecked(v);return b;}private LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setPadding(0,dp(3),0,dp(5));return r;}private LinearLayout.LayoutParams weight(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(50),1);p.setMargins(dp(2),0,dp(2),0);return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private interface S{void run(int v);}private SeekBar slider(int v,S a){SeekBar b=new SeekBar(this);b.setMax(100);b.setProgress(v);b.setOnSeekBarChangeListener(change((x,n)->a.run(n)));return b;}private SeekBar sliderNoInvalidate(int v,S a){return slider(v,a);}private interface C{void run(SeekBar b,int v);}private SeekBar.OnSeekBarChangeListener change(C c){return new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int v,boolean u){if(u&&!uiChanging)c.run(b,v);}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}};}
    private Spinner spinner(String[]v,int pos){Spinner s=spinnerNoInvalidate(v,pos);s.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?>p,View v,int x,long id){if(!uiChanging)changed();}public void onNothingSelected(AdapterView<?>p){}});return s;}private Spinner spinnerNoInvalidate(String[]v,int pos){Spinner s=new Spinner(this);ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,v);a.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);s.setAdapter(a);s.setSelection(pos);return s;}private SeekBar gain(TextView t,String prefix){SeekBar b=new SeekBar(this);b.setMax(100);b.setProgress(50);b.setOnSeekBarChangeListener(change((x,v)->{t.setText(prefix+": "+(50+v)+"%");changed();}));return b;}

    private void changed(){if(uiChanging)return;invalidateCache();previewCurrent();}
    private void invalidateCache(){configGen.incrementAndGet();cacheReady=false;cacheGen=-1;if(cacheFile!=null){try{cacheFile.delete();}catch(Throwable ignored){}cacheFile=null;}}
    private void openMedia(){stopAll();Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"image/*","video/*"});startActivityForResult(i,REQ_OPEN);}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();if(req==REQ_OPEN){try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Throwable ignored){}loadSource(u);}else if(req==REQ_SAVE)renderWav(u);}
    private void loadSource(Uri u){invalidateCache();sourceUri=u;status.setText("Decoding source…");worker.submit(()->{try{releaseSource();ContentResolver cr=getContentResolver();String mime=cr.getType(u),lower=u.toString().toLowerCase(Locale.US);if(mime!=null&&mime.startsWith("video/")){sourceKind=VIDEO;retriever=new MediaMetadataRetriever();retriever.setDataSource(this,u);durationMs=parseLong(retriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION),1000);sourceWidth=parseInt(retriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH),640);sourceHeight=parseInt(retriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_HEIGHT),480);Bitmap first=getVideoFrame(0);if(first==null)throw new IllegalStateException("Video decoder returned no frame");runOnUiThread(()->{sourcePreview.setImageBitmap(first);presetVideo();previewBitmap(first);});}else if((mime!=null&&mime.equals("image/gif"))||lower.endsWith(".gif")){sourceKind=GIF;gifBytes=readAll(cr.openInputStream(u));gifMovie=Movie.decodeByteArray(gifBytes,0,gifBytes.length);durationMs=gifMovie==null?0:Math.max(1000,gifMovie.duration());if(gifMovie==null){sourceKind=IMAGE;stillBitmap=decodeBitmap(u);durationMs=6000;runOnUiThread(()->{sourcePreview.setImageBitmap(stillBitmap);previewBitmap(stillBitmap);});}else{sourceWidth=gifMovie.width();sourceHeight=gifMovie.height();Bitmap first=getGifFrame(0);runOnUiThread(()->{sourcePreview.setImageBitmap(first);presetVideo();previewBitmap(first);});}}else{sourceKind=IMAGE;stillBitmap=decodeBitmap(u);if(stillBitmap==null)throw new IllegalStateException("Image decode failed");durationMs=6000;runOnUiThread(()->{sourcePreview.setImageBitmap(stillBitmap);previewBitmap(stillBitmap);});}}catch(Throwable t){runOnUiThread(()->status.setText("Load error: "+safe(t)));}});}

    private V9TraceEngine.Settings settings(){V9TraceEngine.Settings s=new V9TraceEngine.Settings();s.sampleRate=sampleRate();s.fps=fps();s.profile=profileSpinner.getSelectedItemPosition();s.quality=qualityBar.getProgress();s.isoBands=2+bandsSpinner.getSelectedItemPosition();s.structure=structureBar.getProgress()/100f;s.tone=toneBar.getProgress()/100f;s.gamma=gamma();s.suppressBorders=borderBox.isChecked();s.invert=invertBox.isChecked();s.xGain=(50+xGainBar.getProgress())/100f;s.yGain=(50+yGainBar.getProgress())/100f;s.rotationDeg=rotation();return s;}private int sampleRate(){int p=sampleSpinner.getSelectedItemPosition();return p==1?96000:p==2?48000:192000;}private int fps(){switch(fpsSpinner.getSelectedItemPosition()){case 1:return 30;case 2:return 24;case 3:return 20;case 4:return 15;default:return 60;}}private float gamma(){return .40f+gammaBar.getProgress()/100f;}private float rotation(){return(rotationBar.getProgress()-120)/10f;}

    private void previewCurrent(){if(sourceKind==NONE||playing.get()||preparing.get())return;worker.submit(()->{try{Bitmap b=currentFrame(0);if(b!=null){V9TraceEngine.Result r=V9TraceEngine.compile(b,settings(),0,Float.NaN,Float.NaN);runOnUiThread(()->showTrace(r,0,"PREVIEW"));}}catch(Throwable ignored){}});}
    private void previewBitmap(Bitmap b){if(b==null)return;worker.submit(()->{try{V9TraceEngine.Result r=V9TraceEngine.compile(b,settings(),0,Float.NaN,Float.NaN);runOnUiThread(()->showTrace(r,0,"PREVIEW"));}catch(Throwable t){runOnUiThread(()->status.setText("Preview error: "+safe(t)));}});}
    private void showTrace(V9TraceEngine.Result r,long frame,String mode){V9TraceEngine.Settings s=cacheSettings!=null&&playing.get()?cacheSettings:settings();V8FrameEngine.Result q=new V8FrameEngine.Result(r.xy,r.rgb,r.samples,s.fps,r.flybacks,r.structureScore,r.lumaScore,1f,r.frameError,r.rmsStep,r.peakStep,r.renderMs,false,mode);scope.setFrame(q);status.setText(String.format(Locale.US,"FRAME %d · %s · %d FPS · %d XY\nPATHS %d · STRUCT %.0f%% · LUMA %.0f%% · ERROR %.1f%%\nFLY %d · RMS %.4f · PEAK %.4f · compile %d ms%s",frame,mode,s.fps,r.samples,r.paths,r.structureScore*100,r.lumaScore*100,r.frameError*100,r.flybacks,r.rmsStep,r.peakStep,r.renderMs,playing.get()?"\nAUDIO "+audio.rate()+" Hz · "+audio.route()+" · underruns "+audio.underruns():""));}

    private void togglePlay(){if(sourceKind==NONE){toast("Load media first.");return;}if(playing.get()||preparing.get()){stopAll();return;}int gen=configGen.get();if(cacheReady&&cacheGen==gen&&cacheFile!=null&&cacheFile.exists())startPrepared();else prepare(true);}
    private void prepare(boolean autoPlay){if(preparing.getAndSet(true))return;cancelPrepare.set(false);playButton.setText("CANCEL PREP");int gen=configGen.get();V9TraceEngine.Settings requested=settings();status.setText("PREPARING reference trace… expensive work happens once, before playback.");worker.submit(()->{File file=null;try{int actual;try{actual=audio.start(requested.sampleRate,requested.fps);}finally{audio.stop();}V9TraceEngine.Settings s=requested.copy();s.sampleRate=actual;int pairs=Math.max(256,Math.round(actual/(float)s.fps));int frames=sourceKind==IMAGE?1:Math.max(1,(int)Math.ceil(Math.max(1,durationMs)*s.fps/1000.0));file=new File(getCacheDir(),"v9_trace_"+System.currentTimeMillis()+".bin");V9PreparedCache.Meta meta=new V9PreparedCache.Meta(actual,s.fps,pairs,frames);float px=Float.NaN,py=Float.NaN;try(V9PreparedCache.Writer w=new V9PreparedCache.Writer(file,meta)){for(int i=0;i<frames;i++){if(cancelPrepare.get()||gen!=configGen.get())throw new InterruptedException("Preparation cancelled");long ms=sourceKind==IMAGE?0:Math.min(Math.max(0,durationMs-1),Math.round(i*1000.0/s.fps));Bitmap b=currentFrame(ms);V9TraceEngine.Result r=V9TraceEngine.compile(b,s,i,px,py);if(r.xy.length>=2){px=r.xy[r.xy.length-2];py=r.xy[r.xy.length-1];}w.write(r);if(i%Math.max(1,s.fps/5)==0){final int pct=Math.min(99,Math.round(100f*i/Math.max(1,frames)));final int ii=i;final long rm=r.renderMs;runOnUiThread(()->status.setText("PREPARING "+pct+"% · frame "+ii+" · compile "+rm+" ms\nPlayback will contain ZERO frame-analysis stalls."));}}}
            if(gen!=configGen.get())throw new InterruptedException("Settings changed");cacheFile=file;cacheReady=true;cacheGen=gen;cacheSettings=s;preparing.set(false);runOnUiThread(()->{playButton.setText("PLAY 60FPS TRACE");status.setText("PREPARED · "+frames+" trace frames · "+s.fps+" fps · "+pairs+" XY/frame\nPressing play now performs no image analysis.");if(autoPlay)startPrepared();});}
        catch(Throwable t){if(file!=null)try{file.delete();}catch(Throwable ignored){}preparing.set(false);runOnUiThread(()->{playButton.setText("PREPARE + PLAY");if(!(t instanceof InterruptedException))status.setText("Prepare error: "+safe(t));else status.setText("Preparation stopped.");});}});}

    private void startPrepared(){if(!cacheReady||cacheFile==null||cacheSettings==null)return;stopPlaybackOnly();V9TraceEngine.Settings s=cacheSettings.copy();int actual;try{actual=audio.start(s.sampleRate,s.fps);}catch(Throwable t){status.setText("Audio start error: "+safe(t));return;}if(actual!=s.sampleRate){audio.stop();invalidateCache();status.setText("Audio route changed sample rate. Rebuilding for "+actual+" Hz…");s.sampleRate=actual;prepare(true);return;}playing.set(true);playButton.setText("STOP");File file=cacheFile;playbackThread=new Thread(()->playCache(file,s),"V9-Prepared-Playback");playbackThread.setPriority(Thread.MAX_PRIORITY);playbackThread.start();}
    private void playCache(File file,V9TraceEngine.Settings s){long global=0,period=Math.round(1_000_000_000.0/s.fps),clock=System.nanoTime();while(playing.get()){try(V9PreparedCache.Reader r=new V9PreparedCache.Reader(file)){V9PreparedCache.Frame f;long local=0;while(playing.get()&&(f=r.next())!=null){long due=clock+global*period;while(playing.get()){long d=due-System.nanoTime();if(d<=0)break;if(d>2_000_000)SystemClock.sleep(Math.min(3,d/1_000_000));else Thread.yield();}if(!playing.get())break;V8FrameEngine.Result q=new V8FrameEngine.Result(f.xy,f.rgb,f.rgb.length,s.fps,countFly(f.xy),0,0,1,0,rms(f.xy),peak(f.xy),0,false,"V9 PREPARED");long fi=local;runOnUiThread(()->{scope.setFrame(q);status.setText(String.format(Locale.US,"FRAME %d · V9 PREPARED · %d FPS · %d XY\nNO COMPILER IN PLAYBACK · FLY %d · RMS %.4f\nAUDIO %d Hz · %s · underruns %d",fi,s.fps,f.rgb.length,q.flybacks,q.rmsStep,audio.rate(),audio.route(),audio.underruns()));});audio.writeFrame(f.xy);global++;local++;}}catch(Throwable t){runOnUiThread(()->status.setText("Playback error: "+safe(t)));break;}}}
    private void stopPlaybackOnly(){playing.set(false);if(playbackThread!=null){playbackThread.interrupt();playbackThread=null;}audio.stop();if(playButton!=null&&!preparing.get())playButton.setText(cacheReady?"PLAY PREPARED":"PREPARE + PLAY");}
    private void stopAll(){cancelPrepare.set(true);preparing.set(false);stopPlaybackOnly();}

    private void chooseSave(){if(sourceKind==NONE){toast("Load media first.");return;}stopPlaybackOnly();Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("audio/wav");i.putExtra(Intent.EXTRA_TITLE,"OsciVision_v9_reference_trace_"+fps()+"fps_"+System.currentTimeMillis()+".wav");startActivityForResult(i,REQ_SAVE);}
    private void renderWav(Uri dest){V9TraceEngine.Settings s=settings();boolean f32=exportSpinner.getSelectedItemPosition()==0;status.setText("Ω TRACE WAV rendering stable geometry…");worker.submit(()->{File tmp=new File(getCacheDir(),"v9_trace_export_"+System.currentTimeMillis()+".wav");try(V4Audio.WavWriter w=V4Audio.createWriter(tmp,s.sampleRate,f32)){int frames=sourceKind==IMAGE?s.fps*6:Math.max(1,(int)Math.ceil(durationMs*s.fps/1000.0));float px=Float.NaN,py=Float.NaN;V9TraceEngine.Result still=null;for(int i=0;i<frames;i++){Bitmap b=sourceKind==IMAGE?stillBitmap:currentFrame(Math.min(Math.max(0,durationMs-1),Math.round(i*1000.0/s.fps)));V9TraceEngine.Result r;if(sourceKind==IMAGE&&still!=null)r=still;else{r=V9TraceEngine.compile(b,s,i,px,py);if(sourceKind==IMAGE)still=r;}px=r.xy[r.xy.length-2];py=r.xy[r.xy.length-1];w.write(r.xy);if(i%Math.max(1,s.fps/4)==0){final int pct=Math.min(99,Math.round(100f*i/Math.max(1,frames)));runOnUiThread(()->status.setText("Ω TRACE WAV · "+pct+"%"));}}try(InputStream in=new BufferedInputStream(new FileInputStream(tmp));OutputStream out=new BufferedOutputStream(getContentResolver().openOutputStream(dest,"w"))){byte[]buf=new byte[65536];int n;while((n=in.read(buf))>0)out.write(buf,0,n);}runOnUiThread(()->status.setText("Saved v9 trace WAV · "+s.fps+" fps · "+s.sampleRate+" Hz"));}catch(Throwable t){runOnUiThread(()->status.setText("Export error: "+safe(t)));}finally{try{tmp.delete();}catch(Throwable ignored){}}});}

    private void showCal(){V8FrameEngine.Settings vs=new V8FrameEngine.Settings();vs.sampleRate=sampleRate();vs.fps=fps();vs.xGain=(50+xGainBar.getProgress())/100f;vs.yGain=(50+yGainBar.getProgress())/100f;vs.rotationDeg=rotation();float[]xy=V8FrameEngine.calCircle(vs);int[]rgb=new int[xy.length/2];java.util.Arrays.fill(rgb,Color.rgb(140,255,185));scope.setFrame(new V8FrameEngine.Result(xy,rgb,rgb.length,fps(),0,1,1,1,0,0,0,0,false,"CAL CIRCLE"));}
    private void presetVideo(){uiChanging=true;fpsSpinner.setSelection(0);profileSpinner.setSelection(0);qualityBar.setProgress(94);structureBar.setProgress(98);toneBar.setProgress(34);bandsSpinner.setSelection(2);uiChanging=false;qualityLabel.setText("VECTOR DETAIL: 94%");structureLabel.setText("STRUCTURE PRIORITY: 98%");toneLabel.setText("TONE / HATCH: 34%");invalidateCache();}
    private Bitmap currentFrame(long ms){if(sourceKind==VIDEO)return getVideoFrame(ms);if(sourceKind==GIF)return getGifFrame(ms);return stillBitmap;}private Bitmap getVideoFrame(long ms){if(retriever==null)return null;long us=Math.max(0,ms)*1000L;try{if(Build.VERSION.SDK_INT>=27){int max=720,w=sourceWidth<=0?max:sourceWidth,h=sourceHeight<=0?max:sourceHeight;float sc=Math.min(1f,max/(float)Math.max(w,h));Bitmap b=retriever.getScaledFrameAtTime(us,MediaMetadataRetriever.OPTION_CLOSEST,Math.max(2,Math.round(w*sc)),Math.max(2,Math.round(h*sc)));if(b!=null)return b;}}catch(Throwable ignored){}return retriever.getFrameAtTime(us,MediaMetadataRetriever.OPTION_CLOSEST);}private Bitmap getGifFrame(long ms){if(gifMovie==null)return null;int max=720,w=Math.max(1,gifMovie.width()),h=Math.max(1,gifMovie.height());float sc=Math.min(1f,max/(float)Math.max(w,h));Bitmap out=Bitmap.createBitmap(Math.max(2,Math.round(w*sc)),Math.max(2,Math.round(h*sc)),Bitmap.Config.ARGB_8888);Canvas c=new Canvas(out);c.drawColor(Color.BLACK);c.scale(sc,sc);synchronized(this){gifMovie.setTime((int)(ms%Math.max(1,durationMs)));gifMovie.draw(c,0,0);}return out;}
    private Bitmap decodeBitmap(Uri u)throws Exception{if(Build.VERSION.SDK_INT>=28){ImageDecoder.Source src=ImageDecoder.createSource(getContentResolver(),u);return ImageDecoder.decodeBitmap(src,(d,info,s)->d.setAllocator(ImageDecoder.ALLOCATOR_SOFTWARE));}try(InputStream in=new BufferedInputStream(getContentResolver().openInputStream(u))){return BitmapFactory.decodeStream(in);}}
    private void releaseSource(){stillBitmap=null;gifMovie=null;gifBytes=null;durationMs=0;sourceWidth=sourceHeight=0;if(retriever!=null){try{retriever.release();}catch(Throwable ignored){}retriever=null;}}
    @Override protected void onDestroy(){stopAll();invalidateCache();releaseSource();worker.shutdownNow();super.onDestroy();}
    private static int countFly(float[]xy){int n=0;for(int i=2;i<xy.length;i+=2){float dx=xy[i]-xy[i-2],dy=xy[i+1]-xy[i-1];if(dx*dx+dy*dy>.075f*.075f)n++;}return n;}private static float rms(float[]xy){double s=0;int n=0;for(int i=2;i<xy.length;i+=2){float dx=xy[i]-xy[i-2],dy=xy[i+1]-xy[i-1];s+=dx*dx+dy*dy;n++;}return(float)Math.sqrt(s/Math.max(1,n));}private static float peak(float[]xy){float p=0;for(int i=2;i<xy.length;i+=2){float dx=xy[i]-xy[i-2],dy=xy[i+1]-xy[i-1];p=Math.max(p,(float)Math.sqrt(dx*dx+dy*dy));}return p;}
    private static byte[]readAll(InputStream in)throws Exception{if(in==null)return new byte[0];try(InputStream x=in;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[]b=new byte[65536];int n;while((n=x.read(b))>0)out.write(b,0,n);return out.toByteArray();}}private static long parseLong(String s,long f){try{return Long.parseLong(s);}catch(Throwable t){return f;}}private static int parseInt(String s,int f){try{return Integer.parseInt(s);}catch(Throwable t){return f;}}private static String safe(Throwable t){if(t==null)return"unknown";String m=t.getMessage();return m==null||m.trim().isEmpty()?t.getClass().getSimpleName():m;}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
